FROM jupyter/minimal-notebook

RUN pip3 install --user \
    torch \
    torchvision

RUN pip3 install --user \
    numpy \
    snakemake \
    pandas \
    chartify \
    matplotlib \
    holidays \
    click \
    pyarrow

RUN PATH=$PATH:/home/jovyan/.local/bin
